id: ABED964B6
title: Short Praise of the Buddha's Deeds
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.011355
  last_modified_at: 2022-03-01 02:13:20.011358
