id: ABED964B6
title: Guru Yoga of the Guru Mahāmuni
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.001963
  last_modified_at: 2022-03-01 02:13:20.001971
