id: ABED964B6
title: 'Praise of the Buddha: With Skilful Means & Compassion...'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.005473
  last_modified_at: 2022-03-01 02:13:20.005476
