id: ABED964B6
title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.017687
  last_modified_at: 2022-03-01 02:13:20.017692
