id: ABED964B6
title: Verses on the Buddha's Previous Lives
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.019299
  last_modified_at: 2022-03-01 02:13:20.019302
