id: ABED964B6
title: Supplication to Lord Buddha together with the Sixteen Arhats
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.012874
  last_modified_at: 2022-03-01 02:13:20.012876
