id: ABED964B6
title: Praise of the Twelve Acts of the Buddha
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:13:20.007654
  last_modified_at: 2022-03-01 02:13:20.007657
